# a. Obtain three 5-year periods from 2002

In [16]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv

# SEED = 204357764
fnames = [  "RNWK" ,"SPNC", "WTBA" ,"PCH", "CSS" , "ESCA" ,"MLR"  ,"KVHI" ,"BH" ,  "BMTC" ,"HVT" ,"BANR", "XCRA" ,"CTS" , "CSGS" ,"FNHC", 
"FRO" , "BOBE", "DNR" , "NATH" ,"CFNB" ,"WTW" , "PGNX", "MBTF" ,"ADTN", "UNT" , "MTG" , "OME"  ,"CCBG" ,"MSTR" ,"STRS" ,"STBA" ,"INDB",
  "CAC" , "HCKT", "CNXN" ,"DORM", "VIVO" ,"OFIX" ,"AMWD" ,"LCUT", "GEO" , "ANH" , "UMPQ", "RDN" , "LHO" , "AIT" , "MDC" , "LWAY" ,"WAC"] 
",".join(fnames)

'RNWK,SPNC,WTBA,PCH,CSS,ESCA,MLR,KVHI,BH,BMTC,HVT,BANR,XCRA,CTS,CSGS,FNHC,FRO,BOBE,DNR,NATH,CFNB,WTW,PGNX,MBTF,ADTN,UNT,MTG,OME,CCBG,MSTR,STRS,STBA,INDB,CAC,HCKT,CNXN,DORM,VIVO,OFIX,AMWD,LCUT,GEO,ANH,UMPQ,RDN,LHO,AIT,MDC,LWAY,WAC'

In [18]:
m = pd.read_csv("problem6_SP500.csv") 
s = pd.read_csv("problem6.csv")

# b. Compute the betas of each stock in each periods
There are 6 missing stocks. I ignored them.

In [25]:
stocknamelist=s.columns.tolist()[2:]

In [ ]:
"['SPNC' 'XCRA' 'BOBE' 'OME' 'LHO' 'WAC'] not in index"

In [31]:
s[stocknamelist].values.shape

(180, 44)

In [45]:
# stock and market value
s1 = s[stocknamelist].values[0:60,:]
m1 = m["^GSPC"].values[0:60]
s2 = s[stocknamelist].values[60:120,:]
m2 = m["^GSPC"].values[60:120]
s3 = s[stocknamelist].values[120:180,:]
m3 = m["^GSPC"].values[120:180]

In [44]:
print(s3.shape,  m3.shape )

(60, 44) (60,)

In [51]:
# stock and market return
sr1 = (s1[1:60,:] - s1[0:59,:])/s1[0:59,:]
mr1 = (m1[1:60] - m1[0:59])/m1[0:59]
sr2 = (s2[1:60,:] - s2[0:59,:])/s2[0:59,:]
mr2 = (m2[1:60] - m2[0:59])/m2[0:59]
sr3 = (s3[1:60,:] - s3[0:59,:])/s3[0:59,:]
mr3 = (m3[1:60] - m3[0:59])/m3[0:59]

In [52]:
# given stock return and market return, compute beta
def get_beta( stock_return , market_return ):
    n = len(market_return)
    market_return_mean = np.mean(market_return)
    stock_return_mean = np.mean(stock_return)
    a = np.sum( ( stock_return -stock_return_mean )*(market_return -market_return_mean ) )
    b = np.sum( (market_return -market_return_mean)*(market_return -market_return_mean ) )
    return a/b

In [57]:
get_beta(sr1[:,1],mr1)

0.36948626628878523

In [58]:
sr1.shape

(59, 44)

In [59]:
beta1 = []
beta2 = []
beta3 = []
for i in range(44):
    beta1.append( get_beta(sr1[:,i],mr1) )
    beta2.append( get_beta(sr2[:,i],mr2) )
    beta3.append( get_beta(sr3[:,i],mr3) )

In [78]:
dat0 = pd.DataFrame({"stock name":stocknamelist})
dat1 = pd.DataFrame({"beta in period 1": beta1})
dat2 = pd.DataFrame({"beta in period 2": beta2})
dat3 = pd.DataFrame({"beta in period 3": beta3})
dat = dat0.join(dat1).join(dat2).join(dat3)
dat

   stock name  beta in period 1  beta in period 2  beta in period 3
0        RNWK          1.406527          1.210995          0.547450
1        WTBA          0.369486          1.010701          1.054764
2         PCH          1.228670          1.006687          1.433328
3         CSS          0.485675          1.023680          1.045040
4        ESCA          1.370619          1.882519          0.553346
5         MLR          1.805918          0.748783          0.589839
6        KVHI          1.378446          1.263330          0.771905
7          BH          1.556675          1.500066          0.304085
8        BMTC          0.505312          0.753248          0.609624
9         HVT          1.191670          0.759626          1.055979
10       BANR          0.927311          2.143556          1.031239
11        CTS          2.465035          2.020708          1.222712
12       CSGS          1.764821          0.857324          1.090776
13       FNHC          1.798962          0.672882          1.750852
14        FRO          1.969172          1.586734          1.955266
15        DNR          0.447416          1.522638          3.424075
16       NATH          0.624337          0.260453          0.384598
17       CFNB          0.448655          0.669184          0.529782
18        WTW          0.417197          1.460053          3.188975
19       PGNX          3.987240          1.398245          3.354266
20       MBTF          0.636684          1.221685          0.061983
21       ADTN          1.836824          1.275388          0.585393
22        UNT          0.274433          1.519778          2.785711
23        MTG          1.679325          3.309854          2.099826
24       CCBG          0.591403          0.803653          0.752471
25       MSTR          2.051396          1.370890          0.931465
26       STRS         -0.127198          1.527269          0.723352
27       STBA          0.575438          0.624294          0.812682
28       INDB          0.958921          1.050658          0.991776
29        CAC          0.518291          0.885638          0.799064
30       HCKT          3.055711          0.942200          0.750457
31       CNXN          2.024886          0.913576          1.576687
32       DORM          0.238107          1.298052          0.654381
33       VIVO          1.313496          0.756021          0.944830
34       OFIX          0.839623          1.017597          0.274037
35       AMWD          1.309965          1.160117          1.385257
36       LCUT          1.265768          2.019380          0.995344
37        GEO          1.785565          0.767063          1.797072
38        ANH          0.966445          0.141563          0.288482
39       UMPQ          0.335808          1.065869          1.164254
40        RDN          1.544636          2.986012          1.592613
41        AIT          0.723035          1.240323          0.952033
42        MDC          1.361558          1.078289          1.299853
43       LWAY          1.367871          0.561203          0.659782

# c. Grouping 1,5,10

In [82]:
datGrouping = dat.sort_values(by=["beta in period 1"], ascending=False )
datGrouping

   stock name  beta in period 1  beta in period 2  beta in period 3
19       PGNX          3.987240          1.398245          3.354266
30       HCKT          3.055711          0.942200          0.750457
11        CTS          2.465035          2.020708          1.222712
25       MSTR          2.051396          1.370890          0.931465
31       CNXN          2.024886          0.913576          1.576687
14        FRO          1.969172          1.586734          1.955266
21       ADTN          1.836824          1.275388          0.585393
5         MLR          1.805918          0.748783          0.589839
13       FNHC          1.798962          0.672882          1.750852
37        GEO          1.785565          0.767063          1.797072
12       CSGS          1.764821          0.857324          1.090776
23        MTG          1.679325          3.309854          2.099826
7          BH          1.556675          1.500066          0.304085
40        RDN          1.544636          2.986012          1.592613
0        RNWK          1.406527          1.210995          0.547450
6        KVHI          1.378446          1.263330          0.771905
4        ESCA          1.370619          1.882519          0.553346
43       LWAY          1.367871          0.561203          0.659782
42        MDC          1.361558          1.078289          1.299853
33       VIVO          1.313496          0.756021          0.944830
35       AMWD          1.309965          1.160117          1.385257
36       LCUT          1.265768          2.019380          0.995344
2         PCH          1.228670          1.006687          1.433328
9         HVT          1.191670          0.759626          1.055979
38        ANH          0.966445          0.141563          0.288482
28       INDB          0.958921          1.050658          0.991776
10       BANR          0.927311          2.143556          1.031239
34       OFIX          0.839623          1.017597          0.274037
41        AIT          0.723035          1.240323          0.952033
20       MBTF          0.636684          1.221685          0.061983
16       NATH          0.624337          0.260453          0.384598
24       CCBG          0.591403          0.803653          0.752471
27       STBA          0.575438          0.624294          0.812682
29        CAC          0.518291          0.885638          0.799064
8        BMTC          0.505312          0.753248          0.609624
3         CSS          0.485675          1.023680          1.045040
17       CFNB          0.448655          0.669184          0.529782
15        DNR          0.447416          1.522638          3.424075
18        WTW          0.417197          1.460053          3.188975
1        WTBA          0.369486          1.010701          1.054764
39       UMPQ          0.335808          1.065869          1.164254
22        UNT          0.274433          1.519778          2.785711
32       DORM          0.238107          1.298052          0.654381
26       STRS         -0.127198          1.527269          0.723352

In [85]:
# here is the index to be regrouping
datGrouping.index.values

array([19, 30, 11, 25, 31, 14, 21,  5, 13, 37, 12, 23,  7, 40,  0,  6,  4,
       43, 42, 33, 35, 36,  2,  9, 38, 28, 10, 34, 41, 20, 16, 24, 27, 29,
        8,  3, 17, 15, 18,  1, 39, 22, 32, 26])

In [86]:
# since I have only 44 stocks
# I'm going to group by 4 and by 11, instead of by 5 and 10

In [126]:
ind = datGrouping.index.values

sr1_4 = []
sr2_4 = []
sr3_4 = []
for j in range(11):
    sr1_4.append( np.mean( sr1[:,ind[4*j:4*j + 4]] , axis= 1) )
    sr2_4.append( np.mean( sr2[:,ind[4*j:4*j + 4]] , axis= 1) )
    sr3_4.append( np.mean( sr3[:,ind[4*j:4*j + 4]] , axis= 1) )
    
sr1_4  =np.transpose( np.array(sr1_4) )
sr2_4  =np.transpose( np.array(sr2_4) )
sr3_4  =np.transpose( np.array(sr3_4) )

sr1_11 = []
sr2_11 = []
sr3_11 = []
for j in range(4):
    sr1_11.append( np.mean( sr1[:,ind[11*j:11*j + 11]] , axis= 1) )
    sr2_11.append( np.mean( sr2[:,ind[11*j:11*j + 11]] , axis= 1) )
    sr3_11.append( np.mean( sr3[:,ind[11*j:11*j + 11]] , axis= 1) )
    
sr1_11  =np.transpose( np.array(sr1_11) )
sr2_11  =np.transpose( np.array(sr2_11) )
sr3_11  =np.transpose( np.array(sr3_11) )

In [127]:
print( sr1.shape, sr1_4.shape, sr1_11.shape)

(59, 44) (59, 11) (59, 4)

In [128]:
sr3_4.shape

(59, 11)

In [129]:
beta1_4 = []
beta2_4 = []
beta3_4 = []
for i in range(11):
    beta1_4.append( get_beta(sr1_4[:,i],mr1) )
    beta2_4.append( get_beta(sr2_4[:,i],mr2) )
    beta3_4.append( get_beta(sr3_4[:,i],mr3) )

In [130]:
#dat0_4 = pd.DataFrame({"stock name":stocknamelist})
dat1_4 = pd.DataFrame({"beta in period 1": beta1_4})
dat2_4 = pd.DataFrame({"beta in period 2": beta2_4})
dat3_4 = pd.DataFrame({"beta in period 3": beta3_4})
dat_4 = dat1_4.join(dat2_4).join(dat3_4)
dat_4

    beta in period 1  beta in period 2  beta in period 3
0           2.889846          1.433011          1.564725
1           1.909200          1.131120          1.176796
2           1.757168          1.401781          1.684631
3           1.471571          1.740101          0.804013
4           1.353386          1.069508          0.864453
5           1.249018          1.236453          1.217477
6           0.923075          1.088343          0.646384
7           0.643865          0.881528          0.537771
8           0.521179          0.821715          0.816603
9           0.420688          1.165644          2.049399
10          0.180288          1.352742          1.331924

In [131]:
beta1_11 = []
beta2_11 = []
beta3_11 = []
for i in range(4):
    beta1_11.append( get_beta(sr1_11[:,i],mr1) )
    beta2_11.append( get_beta(sr2_11[:,i],mr2) )
    beta3_11.append( get_beta(sr3_11[:,i],mr3) )
dat1_11 = pd.DataFrame({"beta in period 1": beta1_11})
dat2_11 = pd.DataFrame({"beta in period 2": beta2_11})
dat3_11 = pd.DataFrame({"beta in period 3": beta3_11})
dat_11 = dat1_11.join(dat2_11).join(dat3_11)
dat_11

   beta in period 1  beta in period 2  beta in period 3
0          2.231412          1.141254          1.418617
1          1.414080          1.611617          1.014026
2          0.842140          0.933645          0.730783
3          0.355744          1.157828          1.452638

# d. Mean Square Error Decomposition

In [146]:
def error_decomp( As , Ps ):
    
    n = len(As)
    
    A_mean = np.mean(As)
    P_mean = np.mean(Ps)
    
    A_sigma2 = np.mean( (As - A_mean)**2  )
    P_sigma2 = np.mean( (Ps - P_mean)**2  )   
    AP_sigma = np.mean( (As - A_mean)*(Ps - P_mean) )
    
    beta = AP_sigma/P_sigma2
    R2 = AP_sigma/A_sigma2
    
    bias = (A_mean - P_mean)**2
    inefficiency = (1 - beta)**2 * P_sigma2
    random = (1-R2) * A_sigma2
    
    
    #print( np.mean( (As- Ps)**2)  - bias - inefficiency - random )
    print(["bias", "inefficiency", "random"])
    return bias, inefficiency, random
    #A.K.A. bias, variance, random

##  individual stock

In [147]:
A = dat['beta in period 1'].values
P = dat['beta in period 2'].values
error_decomp(A,P)

['bias', 'inefficiency', 'random']

(5.8588662757648784e-08, 0.22966551661032319, 0.54734557305305509)

##  4 stocks

In [148]:
A = dat_4['beta in period 1'].values
P = dat_4['beta in period 2'].values
error_decomp(A,P)

['bias', 'inefficiency', 'random']

(5.8588662757648784e-08, 0.0069897964282128813, 0.48554387989676978)

##  11 stocks

In [149]:
A = dat_11['beta in period 1'].values
P = dat_11['beta in period 2'].values
error_decomp(A,P)

['bias', 'inefficiency', 'random']

(5.8588662757756278e-08, 0.007745348628340574, 0.44800857346321515)

## conclusion
more stock makes the inefficiency smaller,  
but the random does improve too much,  
bias is always small